[package]
name = "audio_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
mutter = "0.2.0" 
tokio = { version = "1.35.1", features = ["full"] }
cpal = "0.15.1"
hound = "3.4.0"  # For saving the recorded audio to a WAV file


